### ISSUE TITLE
Formatting summary page

### ISSUE THREAD

**Issue by ddmorgan** [uw-cmg/MAST-ML#113]
Could we add sections to summary html file, with bold titles separating sections?   E.g., full fits, CV, etc.  You have some of this already.  Might help see things fast.  Also, can we organize with rows as well, say 3 figs per row?  That would make for much more compact and quick to use output.

**Comment by rjacobs914** [comment]
No longer relevant for current mastml version- closing. Currently use structured json metadata file with data from each run
