### ISSUE TITLE
Add post processing capability to plotting

### ISSUE THREAD

**Issue by bafflerbach** [uw-cmg/MAST-ML#118]
Similar to current filtering capability add ability to perform post-processing before plots are generated. Initial use would be able to set any negatie values to 0 for a given model.

**Comment by rjacobs914** [comment]
Not sure what is meant here- is this different from being able to modify plots through the generated Jupyter notebooks?

**Comment by rjacobs914** [comment]
No longer relevant for current mastml version- closing
