### ISSUE TITLE
inconsistent feature selection in K-Fold and SingleFit

### ISSUE THREAD

**Issue by yuchenliu119** [uw-cmg/MAST-ML#149]
I performed a feature selection and chose the test_cases to be SingleFit and K-FoldCV simultaneously, but it turns out to return total different feature selections in the README files. I attached the test.conf the datasets and the corresponding results.

[problem_yuchen.zip](https://github.com/uw-cmg/MAST-ml-private/files/1877124/problem_yuchen.zip)

**Comment by rjacobs914** [comment]
@yuchenliu119 
Not clear to me this is an issue. It looks like you ran the two different KFoldCV tests with different feature sets. Maybe one was done with feature selection while the other wasn't? In particular, the linear model one looks like all features were used.
