### ISSUE TITLE
Add standardized errors (ie, divide by std dev) to basic output on plots

### ISSUE THREAD

**Issue by ddmorgan** [uw-cmg/MAST-ML#158]

**Comment by qpwo** [comment]
Can you explain this further?

**Comment by ddmorgan** [comment]
Yes - the idea is that RMSE is useful but RMSE/sigma is more useful.   Sigma is the standard deviation of the Y values of the total data set.  I would like to add to the std text on the plots the value of sigma.  We could also add RMSE/sigma but maybe that is too much.  Just having sigma would be excellent.  I ask people for this value all the time and people don't know if we just have the output figures.
