### ISSUE TITLE
Add cluster CV

### ISSUE THREAD

**Issue by ddmorgan** [uw-cmg/MAST-ML#165]
We should add an automated kmeans clustering or related that then uses the clusters for CV.  This is what Citrine does for better error estimates.

**Comment by qpwo** [comment]
Yeah we can definitely do this. Will get started on Monday. We already have split-by-group, which is the same thing.

**Comment by qpwo** [comment]
Oh actually this is a little different from split-by-group. That algorithm assumes you have the classes in a column, but for cluster-cross-validation, you would have to create your own clusters, like you said. Yeah, we can do this

**Comment by rjacobs914** [comment]
now implemented
