### ISSUE TITLE
duplicate features from feature generation

### ISSUE THREAD

**Issue by HaijinLu** [uw-cmg/MAST-ML#168]
should remove some duplicate features (different column names with identical values), arithmetic_average and composition_average may be the same in some cases.

**Comment by robertmaxwilliams** [comment]
I think this step should remove repeats successfully (including from input):
https://github.com/uw-cmg/MAST-ML/blob/23d763482265e2cf02b11726d36deb0296cb737e/mastml/mastml.py#L174

It is on the current dev branch.

**Comment by rjacobs914** [comment]
yes, this is no longer an issue
