### ISSUE TITLE
Error with file path when making plots

### ISSUE THREAD

**Issue by vmeschke** [uw-cmg/MAST-ML#169]
[log.log](https://github.com/uw-cmg/MAST-ML/files/2233252/log.log)

Using dev_Ryan branch.

**Comment by robertmaxwilliams** [comment]
The issue seems to be the leading slash on the filepath, we haven't tested everything on windows. I'll try to locate where that slash is getting prepended.

**Comment by rjacobs914** [comment]
It's line 226 in plot_helper I think

**Comment by robertmaxwilliams** [comment]
Yes, I believe that is the issue. @rjacobs914 Do you know how to replace that with the proper calls to `os.path` to make it platform independent? I can take a swing at it tonight, I've used `path` a lot.

**Comment by robertmaxwilliams** [comment]
Sorry hit the wrong button :\
Yes, I believe that is the issue. @rjacobs914 Do you know how to replace that with the proper calls to `os.path` to make it platform independent?

**Comment by rjacobs914** [comment]
Fixed it. os.path.dirname() to the rescue!
