### ISSUE TITLE
For clustering, add k-medoids method. Not in sklearn so will need to use another package, quick google search shows several options

### ISSUE THREAD

**Issue by rjacobs914** [uw-cmg/MAST-ML#174]

**Comment by ddmorgan** [comment]
This should have said k-means method.  This is in scikitlearn  http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html

**Comment by rjacobs914** [comment]
This is different from k-means, which is in sklearn as you said

**Comment by ddmorgan** [comment]
Oops - got it. This is a different method.  I see.  But we might use kmeans also.

**Comment by rjacobs914** [comment]
this is available in newer mastml versions
