### ISSUE TITLE
Mixed forward selection method

### ISSUE THREAD

**Issue by ddmorgan** [uw-cmg/MAST-ML#191]
I think we should code a mixed forward selection method that let's you do the following.

1. For the first n features choose them by hand or perform a comprehensive search of all feature combinations.  Note that the latter scales as N choose n (N=total # of features) which can be very large so the routine should output this value as a guide and come with a warning when this number is large, say >10^4 or 10^5.

2. Then do forward selection for remaining features n+1 to N total features.

This could be a key benefit for forward selection.

**Comment by rjacobs914** [comment]
This was implemented into the MASTMLFeatureSelector routine- closing.
