### ISSUE TITLE
simultaneous explicit choice of features and not_input_features is allowed and produces an error instead of telling whats wrong

### ISSUE THREAD

**Issue by mppolak** [uw-cmg/MAST-ML#201]
raises an error connected with the specified not_input_feature name
i'm working on it

**Comment by mppolak** [comment]
fixed in my branch
I raised an exception but maybe there should be a warning and no_input_features should be automatically reset to empty?

**Comment by mppolak** [comment]
added the warning option in my branch as a comment, uncomment or remove depending on which is better

**Comment by rjacobs914** [comment]
Should be fixed in latest branch
