### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by mppolak** [uw-cmg/MAST-ML#207]
Please change the installation instruction:
git clone ssh://git@github.com/uw-cmg/MAST-ML

to:
git clone https://github.com/uw-cmg/MAST-ML.git

Otherwise you'll get:
_Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists._

Also, the README.md shoud say the same as the manual

**Comment by Nakzz** [comment]
Submitted pull request!

**Comment by rjacobs914** [comment]
The git clone line has been updated in the Readme (will push to master soon, currently in error_analysis branch)
