### ISSUE TITLE
Dependencies should be added to setup.py

### ISSUE THREAD

**Issue by Nakzz** [uw-cmg/MAST-ML#211]
I am having to install the following packages manually with pip, but these could be added to setup.py

Cython-0.29.13
pytest-5.0.1
mlxtend-0.17.0
dominate-2.3.5
matminer-0.5.8
scikit-optimize-0.13.2 (aka 'skopt' but pip can't find skopt)

Should I do a PR with the following modules added?

**Comment by rjacobs914** [comment]
I have added all needed dependencies in updated setup.py file
