### ISSUE TITLE
A runtime exception has occured

### ISSUE THREAD

**Issue by Amir1361** [uw-cmg/MAST-ML#213]
Hi
I have the following error in running MAST-ML package. 
([ERROR] unsupported operand type(s) for /: 'str' and 'int')
This is my input file:
[GeneralSetup]
    input_features =  Mo RPM, Nb RPM, Ta RPM, W RPM
    input_target = Mo
    #randomizer = False
    metrics = Auto
    #grouping_feature = campaign_number

[FeatureNormalization]
    [[MinMaxScaler]]

[DataSplits]
    [[LeaveOneOut]]
    
[Models]
    
	[[KernelRidge_linear]]
    	        alpha = 1
		kernel = linear

[HyperOpt]
    [[GridSearch_KernelRidgelinear]]
                estimator = KernelRidge_linear
                cv = LeaveOneOut
                param_names = alpha
                param_values = -5 5 100 log float
                scoring = root_mean_squared_error
    
[MiscSettings]
    plot_target_histogram = True
    plot_train_test_plots = True
    plot_predicted_vs_true = True
    plot_predicted_vs_true_average = True
    plot_best_worst_per_point = True
    plot_each_feature_vs_target = False
    plot_error_plots = True
    rf_error_method = stdev
    rf_error_percentile = 95
    normalize_target_feature = False
Could you please help me to solve this issue?
Thanks
Amir

**Comment by rjacobs914** [comment]
At first glance your input file looks good.

Can you confirm that all of your input features are ints/floats and there are no strings present?

Also, are you loading in the data file as a .csv or .xlsx? Sometimes the .csv files can have issues with hidden characters getting interpreted as strings. If you are using .csv I would try saving as .xlsx and using that as the input data file.

**Comment by Amir1361** [comment]
Thanks for your reply. I changed my data file from .csv to .xlsx, but I have again the same error. Here is the files inside the results folder.
[data.xlsx](https://github.com/uw-cmg/MAST-ML/files/3914374/data.xlsx)
[errors.log](https://github.com/uw-cmg/MAST-ML/files/3914375/errors.log)
[log.log](https://github.com/uw-cmg/MAST-ML/files/3914376/log.log)

**Comment by rjacobs914** [comment]
No longer relevant for current mastml version- closing
