### ISSUE TITLE
Some final TODO updates for EnsembleRegressor and RvE plots:

### ISSUE THREAD

**Issue by alexp205** [uw-cmg/MAST-ML#221]
- EnsembleRegressor's `stats_check_models` is currently 1) using a fixed threshold (alpha) of 0.01, and 2) NOT eliminating failed models and re-calculating results. This can easily be fixed by adding two specification fields in the conf file and then passing them into the EnsembleRegressor constructor before being referenced in the `stats_check_models` function. Note that Prof. Morgan wanted a specification of how many sigmas away from the mean before models are considered failed, but the conversion from number of sigmas to alpha threshold is non-trivial (but well documented in statistics)
- binning in RvE plots is currently adaptable through the specification of two parameters: `num_error_bins` and `last_error_bin`. Prof. Morgan wanted a third option of describing bin resolution through a bin width. Note that we can't use all three or we end up with a potentially conflicting specification. The logic for automatically generating the bins using bin width as a parameter is not implemented, nor is the logic for handling specification of all three parameters

**Comment by rjacobs914** [comment]
No longer relevant for current mastml version- closing. The Ensemble regressor now uses sklearn's BaggingRegressor method
