### ISSUE TITLE
Calibration File for Linear Regression Model

### ISSUE THREAD

**Issue by negiutsav9** [uw-cmg/MAST-ML#248]
Hi, I am trying to create a linear regression model with calibrated error bars. However, I am getting the following error

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/55469943/202813813-41f6cb10-6a21-4a44-9901-e3c89e10ea2b.png">

Due to the above error, I am unable to upload my model to the foundry as the model doesn't have a calibration file. 

<img width="728" alt="image" src="https://user-images.githubusercontent.com/55469943/202814087-f02ad220-25f7-4ee9-bb74-14b060e83a16.png">

Are there any workarounds for uploading linear regression model?

Thanks

**Comment by rjacobs914** [comment]
Linear regression doesn't support error bar recalibration as it doesn't output error bars. If you want error bars, you'll need to make an ensemble of linear models. Do note that the recalibration file is optional for submission of a Foundry model with mastml
