### ISSUE TITLE
doc note multiprocessing and ParamOptGA

### ISSUE THREAD

**Issue by cmgtam** [uw-cmg/MAST-ML#40]
Make sure virtual memory (and memory) are large enough for ParamOptGA

Note that morgan3 apparently works without setting pvmem tag (otherwise actually limits pvmem to 1000mb which is not enough) while morgan2 with pvmem tag gives unlimited pvmem

qstat -f <jobid> | grep used to see resource usage

**Comment by rjacobs914** [comment]
paramoptga no longer used
