### ISSUE TITLE
Permission error when save path not set as current directory

### ISSUE THREAD

**Issue by bafflerbach** [uw-cmg/MAST-ML#46]
if save_path is ./"anything" I am seeing a permission error when writing MASTMLlog.log

File "C:\ProgramData\Anaconda2\envs\ML\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another pro
cess: 'C:\\Users\\Ben\\Documents\\GitHub\\mast-ml-data\\DATA_solute_diffusion_class_update\\MASTMLlog.log
' -> 'C:\\Users\\Ben\\Documents\\GitHub\\mast-ml-data\\DATA_solute_diffusion_class_update\\test_paper_nor
malization\\MASTMLlog.log'

This may be related to the fact that it looks like the code is writing MASTMLlog.log to both the specified save directory and working directory that the code is run from.

**Comment by rjacobs914** [comment]
no longer an issue
