### ISSUE TITLE
Identify test and training data within one input file

### ISSUE THREAD

**Issue by ddmorgan** [uw-cmg/MAST-ML#54]
It should be possible to identify certain data to fit and other to predict from within one file.  This is obviously done in CV but should be a flexible routine one uses for all CV and which you can use to do specific exclusions outside a full CV test of specific subsets of the data.  One should be able to do single cases or loops over many cases.

**Comment by qpwo** [comment]
Can you explain this more? Like would the user specify rows like this?
```
train_rows = 0:1445
test_rows = 1445:2000
```
How else could the user specify what data is train and what data is test, aside from cross validation?

**Comment by rjacobs914** [comment]
this is now implemented with user-specified validation columns
