### ISSUE TITLE
jupyter notebook incomplete ticklabels

### ISSUE THREAD

**Issue by bafflerbach** [uw-cmg/MAST-ML#79]
The ticklabels in the jupyter notebook don't pull in all of the ticks and therefore some ticks are unlabeled

        ax.set_xticks([-10.0, -8.0, -6.0, -4.0, -2.0])
        ax.set_xticklabels(['', '−8', '−6', '−4', ''], rotation=0.0)

**Comment by rjacobs914** [comment]
No longer relevant for current mastml version- closing
