### ISSUE TITLE
cluster plotting fails (fix with user setup)

### ISSUE THREAD

**Issue by cmgtam** [uw-cmg/MAST-ML#86]
Cluster plotting fails with no display because there is no display on the cluster, and the default backend is Qt5Agg.
Fix for this and other backend errors is matplotlibrc configuration file, especially because by the time MASTML.py is called, sometimes it is already too late to set the backend (anaconda may have already set it, etc.)

Documentation added in commits:
cbba179255a59574079d5c3c45e52c535d0f4ebf
e49d6915cec296e3a2e39834fe8e242552447204
cf9787e652509e0dfa5a3d062331f6bb0823d661

MASTML now gives information about the backend matplotlib is using and the config file matplotlib is using:
commit 59be68ad97e03ac03efc077f88e7666be90d41fa
commit aabdebbace5a24be0461a5cfacfe1960d2b5e738

@bafflerbach Notify Ben. Change is not yet in dev, only on classes branch right now.

**Comment by rjacobs914** [comment]
No longer relevant for current mastml version- closing
